name: video_thumbnail_gen
description: >
  A production-grade Flutter plugin to generate video thumbnails on Android and iOS.
  Supports JPEG, PNG, WebP, HEIC, batch extraction, metadata, and custom caching.
version: 0.7.0
homepage: https://github.com/Itsxhadi/video_thumbnail_gen
repository: https://github.com/Itsxhadi/video_thumbnail_gen
issue_tracker: https://github.com/Itsxhadi/video_thumbnail_gen/issues
topics:
  - video
  - thumbnail
  - media
  - youtube
  - video-thumbnail
funding:
  - https://www.paypal.com/donate/?hosted_button_id=VV3WVVCZDF6TC

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.itsxhadi.video_thumbnail
        pluginClass: VideoThumbnailPlugin
      ios:
        pluginClass: VideoThumbnailPlugin
